Repository voiapp/zephyr, pull requests merged in 2021-12, with the labels that each got.

#33 Set the CMP0116 policy to be compatible with newer cmake (>=3.20)
  cmake/app/boilerplate.cmake
Labels: area: Build System

#32 net: lwm2m: Made pmin and pmax attributes optional
  subsys/net/lib/lwm2m/Kconfig
  subsys/net/lib/lwm2m/lwm2m_engine.c
Labels: area: Networking

#34 driver: modem: Fix mux device name comparison
  drivers/modem/modem_iface_uart.c
Labels: area: Modem
